config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                     Controller#Action
#                      root GET    /                               dashboards#index
#         new_admin_session GET    /admins/sign_in(.:format)       admins/sessions#new
#             admin_session POST   /admins/sign_in(.:format)       admins/sessions#create
#     destroy_admin_session DELETE /admins/sign_out(.:format)      admins/sessions#destroy
#        new_admin_password GET    /admins/password/new(.:format)  admins/passwords#new
#       edit_admin_password GET    /admins/password/edit(.:format) admins/passwords#edit
#            admin_password PATCH  /admins/password(.:format)      admins/passwords#update
#                           PUT    /admins/password(.:format)      admins/passwords#update
#                           POST   /admins/password(.:format)      admins/passwords#create
# cancel_admin_registration GET    /admins/cancel(.:format)        admins#cancel
#    new_admin_registration GET    /admins/sign_up(.:format)       admins#new
#   edit_admin_registration GET    /admins/edit(.:format)          admins#edit
#        admin_registration PATCH  /admins(.:format)               admins#update
#                           PUT    /admins(.:format)               admins#update
#                           DELETE /admins(.:format)               admins#destroy
#                           POST   /admins(.:format)               admins#create
#                 dashboard GET    /dashboard(.:format)            dashboards#index
#

Rails.application.routes.draw do

  root to: 'dashboards#index'

  get 'dashboard', to: 'dashboards#index'
  get 'claims', to: 'dashboards#claims'
  get 'vendors', to: 'dashboards#vendors'


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins'
  }

  resources :admins
  resources :policies

  resources :vendors 
  get 'vendor_expire', to: 'vendors#index'

end

app/views/menus/_general.html.erb
<li class="navigation__sub navigation__sub--toggled">
  <a href=""><i class="fa fa-tint"></i> General </a>
  <ul style="display: block;">
    <li><%= link_to("<i class='fa fa-list'></i> Policies".html_safe, policies_path) %></li>
    
  </ul>
</li>

app/views/menus/_navigator.html.erb
<aside class="sidebar">
  <div class="scrollbar-inner">
    <div class="user">
      <div class="user__info" data-toggle="dropdown">
        <%= image_tag("avatars/aaron-henderson.jpg", class: 'user__img') %>

        <div>
          <div class="user__name">Aaron Henderson</div>
          <div class="user__email">aaron@buildit.io</div>
        </div>
      </div>

      <div class="dropdown-menu">
        <%= link_to("<i class='zmdi zmdi-assignment-account'></i> &nbsp View Profile ".html_safe, "/admins/#{current_admin.id}/edit", class: 'dropdown-item')%>
        <%= link_to("<i class='zmdi zmdi-power'></i> &nbsp Sign Out".html_safe, destroy_admin_session_path, method: :delete, class: 'dropdown-item') %>
      </div>
    </div>

    <ul class="navigation">

      <%= render partial: '/menus/general' %>
      <%= render partial: '/menus/tools'  %>
      <%= render partial: '/menus/security' %>
      <%= render partial: '/menus/setup'  %>

    </ul>
  </div>
</aside>

app/views/menus/_security.html.erb
<li class="navigation__sub navigation__sub--toggled">
  <a href="" data-ma-action="submenu-toggle"><i class="fa fa-male"></i> Security </a>
  <ul style="display: none;">
    <li><%= link_to("<i class='fa fa-users'></i> Administrators".html_safe, admins_path) %></li>
    <li><%#= link_to("<i class='fa fa-gears'></i> Tools".html_safe, tools_path) %></li>
  </ul>
</li>

app/views/menus/_setup.html.erb
<li class="navigation__sub navigation__sub">
  <a href="" data-ma-action="submenu-toggle"><i class="fa fa-gear"></i> Policy Setup </a>
  <ul style="display: none;">
    <li><%= link_to("<i class='fa fa-gear'></i> Status Codes".html_safe, admins_path) %></li>
    <li><%#= link_to("<i class='fa fa-gears'></i> Tools".html_safe, tools_path) %></li>
  </ul>
</li>

app/views/menus/_tools.html.erb
<li class="navigation__sub navigation__sub--toggled">
	<a href=""><i class="fa fa-wrench"></i> Toolbelt</a>
  <ul style="display: none;">
    <li><%= link_to("<i class='fa fa-arrow-down'></i> Exports".html_safe, vendors_path) %></li>
    <li><%= link_to("<i class='fa fa-arrow-up'></i> Imports".html_safe, vendors_path) %></li>
  </ul>
</li>