config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                     Controller#Action
#                      root GET    /                               dashboards#index
#         new_admin_session GET    /admins/sign_in(.:format)       admins/sessions#new
#             admin_session POST   /admins/sign_in(.:format)       admins/sessions#create
#     destroy_admin_session DELETE /admins/sign_out(.:format)      admins/sessions#destroy
#        new_admin_password GET    /admins/password/new(.:format)  admins/passwords#new
#       edit_admin_password GET    /admins/password/edit(.:format) admins/passwords#edit
#            admin_password PATCH  /admins/password(.:format)      admins/passwords#update
#                           PUT    /admins/password(.:format)      admins/passwords#update
#                           POST   /admins/password(.:format)      admins/passwords#create
# cancel_admin_registration GET    /admins/cancel(.:format)        admins#cancel
#    new_admin_registration GET    /admins/sign_up(.:format)       admins#new
#   edit_admin_registration GET    /admins/edit(.:format)          admins#edit
#        admin_registration PATCH  /admins(.:format)               admins#update
#                           PUT    /admins(.:format)               admins#update
#                           DELETE /admins(.:format)               admins#destroy
#                           POST   /admins(.:format)               admins#create
#                 dashboard GET    /dashboard(.:format)            dashboards#index
#

Rails.application.routes.draw do

  root to: 'dashboards#index'

  get 'dashboard', to: 'dashboards#index'
  get 'claims', to: 'dashboards#claims'
  get 'vendors', to: 'dashboards#vendors'


  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins'
  }

  resources :admins
  resources :policies

  resources :vendors 
  get 'vendor_expire', to: 'vendors#index'

end

app/views/admins/_form.html.erb
<%= form_for resource, html: {id: "form-admin"} do |f| %>
<div class="card-body card-padding">

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <div class="fg-line">
          <label class="">Email Address</label>
          <%= f.text_field :email, class: "form-control", placeholder: "e.g. peter.pan@neverland.com" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <div class="fg-line">
          <label class="">First Name</label>
          <%= f.text_field :first_name, class: "form-control", placeholder: "e.g. Peter" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <div class="fg-line">
          <label class="">Last Name</label>
          <%= f.text_field :last_name, class: "form-control", placeholder: "e.g. Pan" %>
        </div>
      </div>
    </div>
  </div>

  <% unless resource.new_record? %>
  <br>
  <h4>Change your password</h4>
  <br>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <div class="fg-line">
          <%= f.label "Password", class: "" %>
          <input type="password" class="form-control input-lg" required placeholder="your secret password" id="admin_password" name="admin[password]">
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <div class="fg-line">
          <%= f.label "Confirm new password", class: "" %>
          <input type="password" class="form-control input-lg" required placeholder="confirm password" id="admin_password_confirmation" name="admin[password_confirmation]">
        </div>
      </div>
    </div>
  </div>

  <%= link_to (resource.new_record? ? 'Create' : 'Update'), "#", class: "btn btn-primary m-t-10 m-r-5 waves-effect", onclick: "$('#form-admin').submit()" %>

</div>

<% end %>

<% unless resource.new_record? %>
<div class="card-body card-padding">

  <div class="row">
    <div class="col-md-9">
      <div class="form-group">
        <div class="fg-line">

          <br>
          <h4>Delete Account</h4>
          <br>
          <p>Once you delete your account, there is no going back. Please be certain.</p>

          <%= link_to 'Delete your account', "/admins/#{}", data: {confirm: 'Destroy this administrator?'}, class: "btn btn-danger m-t-10 m-r-5 waves-effect", method: :delete %>

        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/admins/_summary.html.erb
<div class="card" id="profile-main">
  <div class=" c-overspark " style="overspark: visible;">
    <div  tabindex="0">
      <div  dir="ltr">

        <div class="pmo-pic">
          <div class="p-relative">
            <a href="">
              <img class="img-responsive mCS_img_loaded" src=<%= asset_url("avatars/aaron-henderson") %> >
            </a>

            <div class="dropdown pmop-message">
              <a data-toggle="dropdown" href="" class="btn bgm-white btn-float z-depth-1 waves-effect waves-circle waves-float">
                <i class="zmdi zmdi-comment-text-alt"></i>
              </a>

              <div class="dropdown-menu">
                <textarea placeholder="Write something..."></textarea>

                <button class="btn bgm-green btn-float waves-effect waves-circle waves-float"><i class="zmdi zmdi-mail-send"></i>
                </button>
              </div>
            </div>

            <a href="" class="pmop-edit">
              <i class="zmdi zmdi-camera"></i> <span class="hidden-xs">Update Profile Picture</span>
            </a>
          </div>


          <div class="pmo-stat">
            <h2 class="m-0 c-white">7</h2>
            Total Connections
          </div>
        </div>

        <div class="t-view m-0">
        <ul class="tvb-stats m-20">
          </ul>
        </div>

        <div class="pmo-block pmo-contact hidden-xs">
          <h2>Contact</h2>
          <ul>
            <li><i class="zmdi zmdi-phone"></i> 678-938-5859</li>
            <li><i class="zmdi zmdi-email"></i> <%= resource.email %></li>
          </ul>
        </div>


        <div class="pmo-block pmo-contact hidden-xs">
          <h2>Mimic User ... coming soon</h2>
          <ul>
            <li><i class="zmdi zmdi-walk"></i> Mimic</li>
            <li><i class="zmdi zmdi-run"></i> BodySnatch</li>
          </ul>
        </div>


      </div>
    </div>
  </div>
</div>

app/views/admins/edit.html.erb
<br>
<br>
<br>
<br>
<div class="content__inner content__inner--sm">
  <header class="content__title">
    <h1>Aaron Henderson</h1>
    <small>Web/UI Developer, Denver, Colorado</small>

    <div class="actions">
      <a href="" class="actions__item zmdi zmdi-trending-up"></a>
      <a href="" class="actions__item zmdi zmdi-check-all"></a>

      <div class="dropdown actions__item">
        <i data-toggle="dropdown" class="zmdi zmdi-more-vert"></i>
        <div class="dropdown-menu dropdown-menu-right">
          <a href="" class="dropdown-item">Refresh</a>
          <a href="" class="dropdown-item">Manage Widgets</a>
          <a href="" class="dropdown-item">Settings</a>
        </div>
      </div>
    </div>
  </header>

  <div class="card profile">
    <div class="profile__img">
      <img src="demo/img/contacts/2.jpg" alt="">

      <a href="" class="zmdi zmdi-camera profile__img__edit"></a>
    </div>

    <div class="profile__info">
      <p>Cras mattis consectetur purus sit amet fermentum. Maecenas sed diam eget risus varius blandit sit amet non magnae tiam porta sem malesuada magna mollis euismod.</p>

      <ul class="icon-list">
        <li><i class="zmdi zmdi-phone"></i> 678-938.5859</li>
        <li><i class="zmdi zmdi-email"></i> aaron@buildit.io</li>
        <li><i class="zmdi zmdi-twitter"></i> @tunacasserole</li>
      </ul>
    </div>
  </div>

  <div class="toolbar">
    <nav class="toolbar__nav">
      <a class="active" href="profile-about.html">About</a>
      <a href="profile-photos.html">Photos</a>
      <a href="profile-contacts.html">Contacts</a>
    </nav>

    <div class="actions">
      <i class="actions__item zmdi zmdi-search" data-ma-action="toolbar-search-open"></i>
    </div>

    <div class="toolbar__search">
      <input type="text" placeholder="Search...">

      <i class="toolbar__search__close zmdi zmdi-long-arrow-left" data-ma-action="toolbar-search-close"></i>
    </div>
  </div>

  <div class="card">
    <div class="card-block">
      <h4 class="card-block__title mb-4">About Aaron Henderson</h4>

      <p>Pellentesque vitae quam quis tellus dignissim faucibus. Suspendisse mattis felis at faucibus lobortis. Sed sit amet tellus dolor. Fusce quis sollicitudin velit. Praesent gravida ullamcorper lectus et tincidunt. Phasellus lectus quam, porta pharetra feugiat in, auctor eget dolor.</p>

      <p>Vestibulum tincidunt imperdiet egestas. In in nunc vitae elit tincidunt tristique id eu justo. Quisque gravida maximus orci, vulputate pharetra mauris commodo at. Mauris eget fermentum ipsum, quis faucibus neque. Fusce eleifend sapien sit amet convallis rhoncus. Proin commodo lacinia lectus, et tempus turpis.</p>

      <br>

      <h4 class="card-block__title mb-4">Contact Information</h4>

      <ul class="icon-list">
        <li><i class="zmdi zmdi-phone"></i>678-938-5859</li>
        <li><i class="zmdi zmdi-email"></i>aaron@buildit.io</li>
        <li><i class="zmdi zmdi-facebook"></i>tunacasserole</li>
        <li><i class="zmdi zmdi-twitter"></i>@tunacasserole</li>
        <li><i class="zmdi zmdi-pin"></i>10638 e. fair pl. 80111/li>
      </ul>
    </div>
  </div>
</div>
</section>

app/views/admins/index.html.erb
<br>
<br>
<br>
<br>
<br>
<section id="content">
  <div class="container">

    <div class="card">
      <div class="card-header ch-alt m-b-20">
        <h2>Administrators</h2>
          <small>Create, modify and grant privileges to hub system administrators.</small>
        <%#= render partial: 'core/actions' %>

        <a href="<%= new_admin_path %>" class="btn bgm-orange btn-float waves-effect"><i class="zmdi zmdi-plus"></i>
        </a>
      </div>

      <div class="table-responsive">
        <table id="grid-admins" class="table">
          <thead>
            <tr>
              <th data-column-id="id" data-type="numeric" data-identifier="true">ID</th>
              <th data-column-id="first_name" data-order="asc" >First Name</th>
              <th data-column-id="last_name">Last Name</th>
              <th data-column-id="email">Email Address</th>
            </tr>
          </thead>
        </table>
      </div>

    </div>

  </div>
</section>

<%= content_for :body_end do %>
<%= init_grid(
              "grid-admins",
              url: "/admins.json",
              primaryKey: "id",
              formatters: {

              },
              handlers: {
                click: { fn: :inspect, url: "/admins", identifier: 'id' }
              }
              ) %>
              <% end %>

app/views/admins/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to "Back to Admins", admins_path %></li>
  <li class="active">New Admin</li>
</ol>

<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <h2>Create a new admin</h2>
              <br>
              <small>Configure a new hub system administrator with roles and privileges </small>
                <%= render partial: 'admins/form', locals: {resource: @admin} %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>